# Copyright (C) DocuSign, Inc.  All rights reserved.
# 
# This source code is intended only as a supplement to DocuSign SDK 
# and/or on-line documentation.
# 
# This sample is designed to demonstrate DocuSign features and is not intended 
# for production use. Code and policy for a production application must be 
# developed to meet the specific data and security requirements of the 
# application.
# 
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.

# Docusign Credentials

development:
  user_name: '<Your Docusign Username Here>'
  password: '<Your Docusign Password Here>'
  account_id: '<Your Docusign Account ID Here>'
  default_endpoint_url: 'https://demo.docusign.net/api/3.0/api.asmx'
  
production:
  user_name: '<Your Docusign Username Here>'
  password: '<Your Docusign Password Here>'
  account_id: '<Your Docusign Account ID Here>'
  default_endpoint_url: 'https://www.docusign.net/api/3.0/api.asmx'
